Supported python 3.8
informalsystems/modelator-py pull request #65
Opened 2022-10-11 10:27 UTC by rnbguy

2022-10-17 13:29 UTC, ivan-gavran requested changes
Approve, would still like to get answers to the two small questions that I asked.

2022-10-17 13:42 UTC, rnbguy commented on modelator_py/util/tla/_intf.py
>  # <https://github.com/tlaplus/tlapm/blob/main/src/pars/intf.ml>
If you notice, the content of this file is mostly invalid. They return some variables which are not defined anywhere. Also, I believe this file is not used anywhere.

2022-10-17 13:45 UTC, rnbguy commented on modelator_py/util/tlc/__init__.py
> +__all__ = ["TlcITFCmd", "tlc_itf"]
This is to make Python linters happy that the imports are being used somehow.

Ref. https://stackoverflow.com/questions/31079047/python-pep8-class-in-init-imported-but-not-used

2022-10-17 14:37 UTC, rnbguy commented on modelator_py/util/tla/_intf.py
>  # <https://github.com/tlaplus/tlapm/blob/main/src/pars/intf.ml>
Because we are not the author of this file :smile: Although, I don't mind removing this file if we eventually use the Chai client.

2022-10-17 16:29 UTC, danwt commented
I can review when the PR opens if needed

2022-10-18 10:18 UTC, rnbguy commented on modelator_py/util/tla/_intf.py
>  # <https://github.com/tlaplus/tlapm/blob/main/src/pars/intf.ml>
@danwt, what do you think? Because you are more aware of that codebase.

2022-10-18 11:44 UTC, danwt commented on modelator_py/util/tla/_intf.py
>  # <https://github.com/tlaplus/tlapm/blob/main/src/pars/intf.ml>
Hmm weird. It seems like documentation. It's probably ok to delete it, maybe in its own commit with a nice commit message.

2022-10-24 13:01 UTC, merged